version: "3.4"

services: 
  auth-api:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    volumes: 
      - ./auth-api:/app
      - /app/node_modules
    env_file: 
      - ./env/.env

  articles-api:
    build:
      context: ./articles-api
      dockerfile: Dockerfile
    ports: 
      - '4000:4000'
    volumes: 
      - ./articles-api:/app
      - /app/node_modules
    env_file: 
      - ./env/.env

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - '5000:8080'
    volumes: 
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on: 
      - auth-api
      - articles-api