version: "3.4"

services: 
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '5000:8080'
    volumes: 
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true