version: "3.4"

services: 
  auth-api:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    volumes: 
      - ./auth-api:/app
      - /app/node_modules
    env_file: 
      - ./auth-api/.env

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '5000:8080'
    volumes: 
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on: 
      - auth-api