apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  selector:
    app: articles
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
        - name: articles
          image: michaeltol/kub-articles-api:latest